name: Build Dockerfile & Uplaod Image 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Step 3: Build, tag, and push Docker image to Amazon ECR
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REPOSITORY: python-images  
        IMAGE_TAG: latest             
      run: |
        # Get the Amazon ECR repository URI
        REPOSITORY_URI=$(aws ecr describe-repositories --repository-names $ECR_REPOSITORY --query 'repositories[0].repositoryUri' --output text)
        
        # Build the Docker image
        docker build -t $ECR_REPOSITORY .
        # Tag Docker image with repository URI and tag
        docker tag $ECR_REPOSITORY:latest $REPOSITORY_URI:$IMAGE_TAG
        # Push the Docker image to Amazon ECR
        docker push $REPOSITORY_URI:$IMAGE_TAG
