name: Build Dockerfile & Upload Image to AWS ECR 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Configure AWS security credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 3: Log in to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Step 4: Build, tag, and upload Docker image to Amazon ECR
    - name: Build, tag, and upload image to Amazon ECR
      
      env:
        ECR_REGISTRY: ${{ steps.login-pf-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{secrets.ECR_REPOSITORY}}
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
